# Missing Values
Missing values kya hain?  = in 

isnull() = in 

isna() = in 

notnull()= in 

notna() = in 

Missing values count = in 

dropna() = in 

fillna()

Fill with mean

Fill with median

Fill with mode

Forward Fill

Backward Fill

# Duplicate Data

duplicated()

drop_duplicates()

Duplicate rows identify karna

Duplicate records remove karna

# Data Types
astype()

Number conversion

pd.to_numeric()

Date conversion

pd.to_datetime()

# Missing Values kya hain?

In [2]:
import pandas as pd

data = {
    "Name": ["Rahul", "Amit", "Neha", "Priya"],
    "Age": [25, 28, None, 30],
    "Salary": [35000, None, 45000, 50000]
}

df = pd.DataFrame(data)

print(df)

    Name   Age   Salary
0  Rahul  25.0  35000.0
1   Amit  28.0      NaN
2   Neha   NaN  45000.0
3  Priya  30.0  50000.0

In [6]:
# Missing Values
#
# Missing value means a value is not available in the dataset.
#
# Missing values are very common in real-world datasets.
#
# Common representations:
# NaN  -> Not a Number
# None -> Python null value
# NaT  -> Missing value for date/time data
#
# Example:
# Age = [25, 28, None, 30]
#
# Here, None represents a missing value.
#
# Why missing values are important:
# 1. They can affect calculations.
# 2. They can affect average and other statistics.
# 3. They can create problems during analysis.
# 4. They need to be identified and handled properly.
#
# Pandas provides different functions to identify and handle
# missing values.

# isnull()

In [13]:
# isnull()
#
# isnull() is used to identify missing values.
#
# It returns:
# True  -> value is missing
# False -> value is not missing
#
# Check complete DataFrame:
# df.isnull()
#
# Check a specific column:
# df["Age"].isnull()
#
# Find rows where Age is missing:
# df[df["Age"].isnull()]
#
# isnull() is mainly used during data cleaning
# to identify missing values.

In [39]:
print(df)

print(df.isnull()) 
print(df["Age"].isnull())  # Kisi particular column par isnull()

print(df[df["Age"].isnull()]) # Missing rows ko identify karna 
#

   Employee_ID   Name   Age Department   Salary  Experience    City
0          101   Amit  25.0         IT  35000.0         2.0   Delhi
1          102  Rahul   NaN         HR  42000.0         4.0  Jaipur
2          103   Neha  29.0       None      NaN         NaN  Mumbai
3          104  Priya  32.0    Finance  55000.0         8.0    None
4          105  Rohit   NaN         IT  48000.0         6.0    Pune
5          106  Pooja  27.0      Sales      NaN         3.0   Delhi
6          107  Ankit  30.0       None  60000.0         NaN    None
7          108  Sneha   NaN         HR  39000.0         5.0  Jaipur
8          109  Vikas  26.0         IT      NaN         2.0  Mumbai
9          110  Kiran  31.0    Finance  52000.0         NaN    Pune
   Employee_ID   Name    Age  Department  Salary  Experience   City
0        False  False  False       False   False       False  False
1        False  False   True       False   False       False  False
2        False  False  False        True    True        True  False
3        False  False  False       False   False       False   True
4        False  False   True       False   False       False  False
5        False  False  False       False    True       False  False
6        False  False  False        True   False        True   True
7        False  False   True       False   False       False  False
8        False  False  False       False    True       False  False
9        False  False  False       False   False        True  False
0    False
1     True
2    False
3    False
4     True
5    False
6    False
7     True
8    False
9    False
Name: Age, dtype: bool
   Employee_ID   Name  Age Department   Salary  Experience    City
1          102  Rahul  NaN         HR  42000.0         4.0  Jaipur
4          105  Rohit  NaN         IT  48000.0         6.0    Pune
7          108  Sneha  NaN         HR  39000.0         5.0  Jaipur

In [40]:
import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Amit", "Rahul", "Neha", "Priya", "Rohit",
             "Pooja", "Ankit", "Sneha", "Vikas", "Kiran"],
    "Age": [25, None, 29, 32, None, 27, 30, None, 26, 31],
    "Department": ["IT", "HR", None, "Finance", "IT",
                   "Sales", None, "HR", "IT", "Finance"],
    "Salary": [35000, 42000, None, 55000, 48000,
               None, 60000, 39000, None, 52000],
    "Experience": [2, 4, None, 8, 6, 3, None, 5, 2, None],
    "City": ["Delhi", "Jaipur", "Mumbai", None, "Pune",
             "Delhi", None, "Jaipur", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)

print(df)

   Employee_ID   Name   Age Department   Salary  Experience    City
0          101   Amit  25.0         IT  35000.0         2.0   Delhi
1          102  Rahul   NaN         HR  42000.0         4.0  Jaipur
2          103   Neha  29.0       None      NaN         NaN  Mumbai
3          104  Priya  32.0    Finance  55000.0         8.0    None
4          105  Rohit   NaN         IT  48000.0         6.0    Pune
5          106  Pooja  27.0      Sales      NaN         3.0   Delhi
6          107  Ankit  30.0       None  60000.0         NaN    None
7          108  Sneha   NaN         HR  39000.0         5.0  Jaipur
8          109  Vikas  26.0         IT      NaN         2.0  Mumbai
9          110  Kiran  31.0    Finance  52000.0         NaN    Pune

In [44]:
print(df)
print(df.isnull())
print(df[df["Age"].isnull()])
print(df["Salary"].isnull())

   Employee_ID   Name   Age Department   Salary  Experience    City
0          101   Amit  25.0         IT  35000.0         2.0   Delhi
1          102  Rahul   NaN         HR  42000.0         4.0  Jaipur
2          103   Neha  29.0       None      NaN         NaN  Mumbai
3          104  Priya  32.0    Finance  55000.0         8.0    None
4          105  Rohit   NaN         IT  48000.0         6.0    Pune
5          106  Pooja  27.0      Sales      NaN         3.0   Delhi
6          107  Ankit  30.0       None  60000.0         NaN    None
7          108  Sneha   NaN         HR  39000.0         5.0  Jaipur
8          109  Vikas  26.0         IT      NaN         2.0  Mumbai
9          110  Kiran  31.0    Finance  52000.0         NaN    Pune
   Employee_ID   Name    Age  Department  Salary  Experience   City
0        False  False  False       False   False       False  False
1        False  False   True       False   False       False  False
2        False  False  False        True    True        True  False
3        False  False  False       False   False       False   True
4        False  False   True       False   False       False  False
5        False  False  False       False    True       False  False
6        False  False  False        True   False        True   True
7        False  False   True       False   False       False  False
8        False  False  False       False    True       False  False
9        False  False  False       False   False        True  False
   Employee_ID   Name  Age Department   Salary  Experience    City
1          102  Rahul  NaN         HR  42000.0         4.0  Jaipur
4          105  Rohit  NaN         IT  48000.0         6.0    Pune
7          108  Sneha  NaN         HR  39000.0         5.0  Jaipur
0    False
1    False
2     True
3    False
4    False
5     True
6    False
7    False
8     True
9    False
Name: Salary, dtype: bool

# isna()

In [45]:
# isna()
#
# isna() is used to identify missing values.
#
# True  -> value is missing
# False -> value is not missing
#
# Check complete DataFrame:
# df.isna()
#
# Check one column:
# df["Age"].isna()
#
# Find rows where Age is missing:
# df[df["Age"].isna()]
#
# isna() and isnull() have the same functionality.

In [51]:
print(df)
print(df.isna())
print(df["Department"].isna())
print(df[df["Salary"].isna()])

   Employee_ID   Name   Age Department   Salary  Experience    City
0          101   Amit  25.0         IT  35000.0         2.0   Delhi
1          102  Rahul   NaN         HR  42000.0         4.0  Jaipur
2          103   Neha  29.0       None      NaN         NaN  Mumbai
3          104  Priya  32.0    Finance  55000.0         8.0    None
4          105  Rohit   NaN         IT  48000.0         6.0    Pune
5          106  Pooja  27.0      Sales      NaN         3.0   Delhi
6          107  Ankit  30.0       None  60000.0         NaN    None
7          108  Sneha   NaN         HR  39000.0         5.0  Jaipur
8          109  Vikas  26.0         IT      NaN         2.0  Mumbai
9          110  Kiran  31.0    Finance  52000.0         NaN    Pune
   Employee_ID   Name    Age  Department  Salary  Experience   City
0        False  False  False       False   False       False  False
1        False  False   True       False   False       False  False
2        False  False  False        True    True        True  False
3        False  False  False       False   False       False   True
4        False  False   True       False   False       False  False
5        False  False  False       False    True       False  False
6        False  False  False        True   False        True   True
7        False  False   True       False   False       False  False
8        False  False  False       False    True       False  False
9        False  False  False       False   False        True  False
0    False
1    False
2     True
3    False
4    False
5    False
6     True
7    False
8    False
9    False
Name: Department, dtype: bool
   Employee_ID   Name   Age Department  Salary  Experience    City
2          103   Neha  29.0       None     NaN         NaN  Mumbai
5          106  Pooja  27.0      Sales     NaN         3.0   Delhi
8          109  Vikas  26.0         IT     NaN         2.0  Mumbai

# notnull()

In [52]:
# notnull()
#
# notnull() is used to identify non-missing values.
#
# True  -> value is available
# False -> value is missing
#
# Check complete DataFrame:
# df.notnull()
#
# Check one column:
# df["Age"].notnull()
#
# Find rows where Age is available:
# df[df["Age"].notnull()]
#
# Find rows where Age and Salary are both available:
# df[df["Age"].notnull() & df["Salary"].notnull()]

In [61]:
print(df)
print(df.notnull())   #Complete DataFrame
print(df["Salary"].notnull())   # Particular column
print(df["City"].notnull())  # Sirf valid rows identify karna

print(df[df["Salary"].notnull() & df["City"].notnull()])  # Multiple conditions

   Employee_ID   Name   Age Department   Salary  Experience    City
0          101   Amit  25.0         IT  35000.0         2.0   Delhi
1          102  Rahul   NaN         HR  42000.0         4.0  Jaipur
2          103   Neha  29.0       None      NaN         NaN  Mumbai
3          104  Priya  32.0    Finance  55000.0         8.0    None
4          105  Rohit   NaN         IT  48000.0         6.0    Pune
5          106  Pooja  27.0      Sales      NaN         3.0   Delhi
6          107  Ankit  30.0       None  60000.0         NaN    None
7          108  Sneha   NaN         HR  39000.0         5.0  Jaipur
8          109  Vikas  26.0         IT      NaN         2.0  Mumbai
9          110  Kiran  31.0    Finance  52000.0         NaN    Pune
   Employee_ID  Name    Age  Department  Salary  Experience   City
0         True  True   True        True    True        True   True
1         True  True  False        True    True        True   True
2         True  True   True       False   False       False   True
3         True  True   True        True    True        True  False
4         True  True  False        True    True        True   True
5         True  True   True        True   False        True   True
6         True  True   True       False    True       False  False
7         True  True  False        True    True        True   True
8         True  True   True        True   False        True   True
9         True  True   True        True    True       False   True
0     True
1     True
2    False
3     True
4     True
5    False
6     True
7     True
8    False
9     True
Name: Salary, dtype: bool
0     True
1     True
2     True
3    False
4     True
5     True
6    False
7     True
8     True
9     True
Name: City, dtype: bool
   Employee_ID   Name   Age Department   Salary  Experience    City
0          101   Amit  25.0         IT  35000.0         2.0   Delhi
1          102  Rahul   NaN         HR  42000.0         4.0  Jaipur
4          105  Rohit   NaN         IT  48000.0         6.0    Pune
7          108  Sneha   NaN         HR  39000.0         5.0  Jaipur
9          110  Kiran  31.0    Finance  52000.0         NaN    Pune

In [6]:
import pandas as pd

data = {
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
    "Customer": ["Amit", "Rahul", "Neha", "Pooja", "Rohit",
                 "Ankit", "Sneha", "Vikas", "Kiran", "Priya"],
    "Product": ["Laptop", "Mobile", "Tablet", None, "Laptop",
                "Mobile", None, "Headphone", "Tablet", "Laptop"],
    "Quantity": [2, 1, None, 3, 1, None, 2, 4, 1, None],
    "Price": [55000, 25000, 30000, 15000, None,
              22000, 18000, None, 28000, 60000],
    "City": ["Delhi", "Jaipur", None, "Mumbai", "Pune",
             "Delhi", "Jaipur", None, "Mumbai", "Pune"]
}

df_sales = pd.DataFrame(data)
print(df_sales)

   Order_ID Customer    Product  Quantity    Price    City
0      1001     Amit     Laptop       2.0  55000.0   Delhi
1      1002    Rahul     Mobile       1.0  25000.0  Jaipur
2      1003     Neha     Tablet       NaN  30000.0    None
3      1004    Pooja       None       3.0  15000.0  Mumbai
4      1005    Rohit     Laptop       1.0      NaN    Pune
5      1006    Ankit     Mobile       NaN  22000.0   Delhi
6      1007    Sneha       None       2.0  18000.0  Jaipur
7      1008    Vikas  Headphone       4.0      NaN    None
8      1009    Kiran     Tablet       1.0  28000.0  Mumbai
9      1010    Priya     Laptop       NaN  60000.0    Pune

In [75]:
print(df_sales)
#Q1.Identify karo ki Price column mein kaun-kaun se values available hain.
print(df_sales["Price"].notnull())

# Q2. Un orders ki complete rows display karo jinki Product information available hai.
print(df_sales[df_sales["Product"].notnull()])

# Q3. Un orders ko identify karo jinki Quantity aur Price dono available hain.
print(df_sales[df_sales["Quantity"].notnull()& df_sales["Price"].notnull()])


# Q4. Un orders ki complete rows display karo jinki City information available hai.

print(df_sales[df_sales["City"].notnull()])

# Q5. ⭐ Real-Life Data Analyst Question
# Sales analysis ke liye un orders ko identify karo jahan Product, Quantity aur Price — teeno information available hain.
print(df_sales[df_sales["Quantity"].notnull() & df_sales["Product"].notnull() & df_sales["Price"].notnull()])

   Order_ID Customer    Product  Quantity    Price    City
0      1001     Amit     Laptop       2.0  55000.0   Delhi
1      1002    Rahul     Mobile       1.0  25000.0  Jaipur
2      1003     Neha     Tablet       NaN  30000.0    None
3      1004    Pooja       None       3.0  15000.0  Mumbai
4      1005    Rohit     Laptop       1.0      NaN    Pune
5      1006    Ankit     Mobile       NaN  22000.0   Delhi
6      1007    Sneha       None       2.0  18000.0  Jaipur
7      1008    Vikas  Headphone       4.0      NaN    None
8      1009    Kiran     Tablet       1.0  28000.0  Mumbai
9      1010    Priya     Laptop       NaN  60000.0    Pune
0     True
1     True
2     True
3     True
4    False
5     True
6     True
7    False
8     True
9     True
Name: Price, dtype: bool
   Order_ID Customer    Product  Quantity    Price    City
0      1001     Amit     Laptop       2.0  55000.0   Delhi
1      1002    Rahul     Mobile       1.0  25000.0  Jaipur
2      1003     Neha     Tablet       NaN  30000.0    None
4      1005    Rohit     Laptop       1.0      NaN    Pune
5      1006    Ankit     Mobile       NaN  22000.0   Delhi
7      1008    Vikas  Headphone       4.0      NaN    None
8      1009    Kiran     Tablet       1.0  28000.0  Mumbai
9      1010    Priya     Laptop       NaN  60000.0    Pune
   Order_ID Customer Product  Quantity    Price    City
0      1001     Amit  Laptop       2.0  55000.0   Delhi
1      1002    Rahul  Mobile       1.0  25000.0  Jaipur
3      1004    Pooja    None       3.0  15000.0  Mumbai
6      1007    Sneha    None       2.0  18000.0  Jaipur
8      1009    Kiran  Tablet       1.0  28000.0  Mumbai
   Order_ID Customer Product  Quantity    Price    City
0      1001     Amit  Laptop       2.0  55000.0   Delhi
1      1002    Rahul  Mobile       1.0  25000.0  Jaipur
3      1004    Pooja    None       3.0  15000.0  Mumbai
4      1005    Rohit  Laptop       1.0      NaN    Pune
5      1006    Ankit  Mobile       NaN  22000.0   Delhi
6      1007    Sneha    None       2.0  18000.0  Jaipur
8      1009    Kiran  Tablet       1.0  28000.0  Mumbai
9      1010    Priya  Laptop       NaN  60000.0    Pune
   Order_ID Customer Product  Quantity    Price    City
0      1001     Amit  Laptop       2.0  55000.0   Delhi
1      1002    Rahul  Mobile       1.0  25000.0  Jaipur
8      1009    Kiran  Tablet       1.0  28000.0  Mumbai

# notna()

In [77]:
# notna()
#
# notna() is used to identify non-missing values.
#
# True  -> value is available
# False -> value is missing
#
# Check complete DataFrame:
# df.notna()
#
# Check one column:
# df["Age"].notna()
#
# Find rows where Age is available:
# df[df["Age"].notna()]
#
# notna() and notnull() have the same functionality.

In [83]:
print(df_sales)
print(df_sales.notna())

print(df_sales["Price"].notna())
print(df_sales[df_sales["City"].notna()])

   Order_ID Customer    Product  Quantity    Price    City
0      1001     Amit     Laptop       2.0  55000.0   Delhi
1      1002    Rahul     Mobile       1.0  25000.0  Jaipur
2      1003     Neha     Tablet       NaN  30000.0    None
3      1004    Pooja       None       3.0  15000.0  Mumbai
4      1005    Rohit     Laptop       1.0      NaN    Pune
5      1006    Ankit     Mobile       NaN  22000.0   Delhi
6      1007    Sneha       None       2.0  18000.0  Jaipur
7      1008    Vikas  Headphone       4.0      NaN    None
8      1009    Kiran     Tablet       1.0  28000.0  Mumbai
9      1010    Priya     Laptop       NaN  60000.0    Pune
   Order_ID  Customer  Product  Quantity  Price   City
0      True      True     True      True   True   True
1      True      True     True      True   True   True
2      True      True     True     False   True  False
3      True      True    False      True   True   True
4      True      True     True      True  False   True
5      True      True     True     False   True   True
6      True      True    False      True   True   True
7      True      True     True      True  False  False
8      True      True     True      True   True   True
9      True      True     True     False   True   True
0     True
1     True
2     True
3     True
4    False
5     True
6     True
7    False
8     True
9     True
Name: Price, dtype: bool
   Order_ID Customer Product  Quantity    Price    City
0      1001     Amit  Laptop       2.0  55000.0   Delhi
1      1002    Rahul  Mobile       1.0  25000.0  Jaipur
3      1004    Pooja    None       3.0  15000.0  Mumbai
4      1005    Rohit  Laptop       1.0      NaN    Pune
5      1006    Ankit  Mobile       NaN  22000.0   Delhi
6      1007    Sneha    None       2.0  18000.0  Jaipur
8      1009    Kiran  Tablet       1.0  28000.0  Mumbai
9      1010    Priya  Laptop       NaN  60000.0    Pune

 # Missing Values Count

In [85]:
# Missing Values Count
#
# To count missing values in each column:
# df.isnull().sum()
#
# isnull() identifies missing values.
# sum() counts the True values.
#
# To count missing values in one column:
# df["Age"].isnull().sum()
#
# Missing values percentage:
# df.isnull().mean() * 100
#
# Missing value count and percentage are very important
# during data cleaning and data quality analysis.

In [5]:
import  pandas as pd

In [16]:
# Q1. Har column mein missing values count karo
df_sales.isnull().sum()

# Q2. City column mein missing values count karo
df_sales["City"].isnull().sum()

# Q3. Product column mein missing values count karo
df_sales["Product"].isnull().sum()

# Q4. Price column mein missing values count karo
df_sales["Price"].isnull().sum()

# Q5. Quantity column mein missing values count karo
df_sales["Quantity"].isnull().sum()

3

# dropna()

In [18]:
# dropna()
#
# dropna() is used to remove missing values.
#
# By default, dropna() removes rows containing
# at least one missing value.
#
# Remove rows with missing values:
# df.dropna()
#
# Remove rows based on specific columns:
# df.dropna(subset=["Price"])
#
# Remove columns containing missing values:
# df.dropna(axis=1)
#
# axis=0 -> rows
# axis=1 -> columns
#
# how="all" removes a row only when
# all values in that row are missing.

In [33]:
# Original DataFrame
df_sales

# Remove rows containing any missing value
df_sales.dropna()

# Remove rows where Price is missing
df_sales.dropna(subset=["Price"])

# Remove missing values from City column
df_sales["City"].dropna()

# Remove rows where City is missing
df_sales.dropna(subset=["City"])

# Remove columns containing missing values
df_sales.dropna(axis=1)

# Remove rows containing missing values
df_sales.dropna(axis=0)

   Order_ID Customer Product  Quantity    Price    City
0      1001     Amit  Laptop       2.0  55000.0   Delhi
1      1002    Rahul  Mobile       1.0  25000.0  Jaipur
8      1009    Kiran  Tablet       1.0  28000.0  Mumbai

In [14]:
import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                    111, 112, 113, 114, 115],

    "Name": ["Amit", "Rahul", "Neha", "Pooja", "Rohit",
             "Sneha", "Vikas", "Kiran", "Ankit", "Priya",
             "Mohit", "Simran", "Raj", "Nisha", "Arjun"],

    "Age": [25, None, 29, 32, None, 27, 30, None, 26, 31,
            None, 28, 34, None, 29],

    "Department": ["IT", "HR", None, "Finance", "IT",
                   "Sales", None, "HR", "IT", None,
                   "Sales", "Finance", "IT", None, "HR"],

    "Salary": [35000, 42000, None, 55000, 48000,
               None, 60000, 39000, None, 52000,
               45000, None, 65000, 41000, None],

    "Experience": [2, 4, None, 8, 6, 3, None, 5,
                   2, None, 4, 7, None, 3, 5],

    "City": ["Delhi", "Jaipur", "Mumbai", None, "Pune",
             "Delhi", None, "Jaipur", "Mumbai", "Pune",
             None, "Delhi", "Jaipur", None, "Mumbai"]
}

df = pd.DataFrame(data)

df

 # 🔹 Part 1 — isnull()

# Q1  Complete DataFrame mein missing values identify karo using isnull().
df.isnull()

# Q2  Age column mein missing values identify karo using isnull().

df['Age'].isnull()

# Q3  Salary column mein missing values identify karo.

df['Salary'].isnull()

# Q4 Un employees ki complete rows display karo jinki Age missing hai.

df[df['Age'].isnull()]

# Q5 Un employees ki complete rows display karo jinki Department missing hai.

df[df["Department"].isnull()]

    Employee_ID   Name   Age Department   Salary  Experience    City
2           103   Neha  29.0       None      NaN         NaN  Mumbai
6           107  Vikas  30.0       None  60000.0         NaN    None
9           110  Priya  31.0       None  52000.0         NaN    Pune
13          114  Nisha   NaN       None  41000.0         3.0    None

In [20]:
## 🔹 Part 2 — isna()
# Q6 Experience column mein missing values identify karo using isna().

df["Experience"].isna()

# Q7 Un employees ki complete rows display karo jinki City missing hai.

df[df["City"].isna()]

#  Q8 Aise employees identify karo jinki Age OR Salary missing hai.

df[(df["Age"].isna()) | (df["Salary"].isna())]

    Employee_ID    Name   Age Department   Salary  Experience    City
1           102   Rahul   NaN         HR  42000.0         4.0  Jaipur
2           103    Neha  29.0       None      NaN         NaN  Mumbai
4           105   Rohit   NaN         IT  48000.0         6.0    Pune
5           106   Sneha  27.0      Sales      NaN         3.0   Delhi
7           108   Kiran   NaN         HR  39000.0         5.0  Jaipur
8           109   Ankit  26.0         IT      NaN         2.0  Mumbai
10          111   Mohit   NaN      Sales  45000.0         4.0    None
11          112  Simran  28.0    Finance      NaN         7.0   Delhi
13          114   Nisha   NaN       None  41000.0         3.0    None
14          115   Arjun  29.0         HR      NaN         5.0  Mumbai

In [24]:
# 🔹 Part 3 — notnull()
# Q9 Un employees ki complete rows display karo jinki Salary available hai.

df[df["Salary"].notnull()]

# Q10  Un employees ki complete rows display karo jinka Department available hai.
df[df["Department"].notnull()]

#Q11 Aise employees identify karo jinki Age AND Experience dono available hain.
# Hint: &
df[(df["Age"].notnull() ) & (df["Experience"].notnull())]

    Employee_ID    Name   Age Department   Salary  Experience    City
0           101    Amit  25.0         IT  35000.0         2.0   Delhi
3           104   Pooja  32.0    Finance  55000.0         8.0    None
5           106   Sneha  27.0      Sales      NaN         3.0   Delhi
8           109   Ankit  26.0         IT      NaN         2.0  Mumbai
11          112  Simran  28.0    Finance      NaN         7.0   Delhi
14          115   Arjun  29.0         HR      NaN         5.0  Mumbai

In [29]:
# 🔹 Part 4 — notna()
# Q12 City mein available values identify karo using notna().

df[df["City"].notna()]

# Q13 Un employees ki complete rows display karo jinki Salary available hai using notna().
df[df["Salary"].notna()]

# Q14 ⭐  Aise employees identify karo jinki Age, Salary aur City teeno available hain.

df[(df["Age"].notna()) & (df["Salary"].notna()) & (df["City"].notna()) ]

    Employee_ID   Name   Age Department   Salary  Experience    City
0           101   Amit  25.0         IT  35000.0         2.0   Delhi
9           110  Priya  31.0       None  52000.0         NaN    Pune
12          113    Raj  34.0         IT  65000.0         NaN  Jaipur

In [36]:
# 🔹 Part 5 — Missing Values Count
# Q15 Har column mein missing values ka count nikalo.

df.isnull().sum()

# Q16 Sirf Age column mein missing values ka count nikalo.

df["Age"].isnull().sum()

# Q17 Sirf Salary column mein missing values ka count nikalo.

df["Salary"].isnull().sum()

# Q18 ⭐ Har column ke missing values ka percentage calculate karo.

df.isnull().mean() * 100

Employee_ID     0.000000
Name            0.000000
Age            33.333333
Department     26.666667
Salary         33.333333
Experience     26.666667
City           26.666667
dtype: float64

In [39]:
# 🔹 Part 6 — dropna()
# Q19 Aisi complete rows remove karo jahan kisi bhi column mein missing value hai.

df.dropna()

#  Q20 ⭐ Real-Life Data Analyst Question
# Employee analysis ke liye sirf un records ko retain karo jahan:
# Age available ho
# Salary available ho
# Department available ho Baaki rows remove karo using dropna().

df[(df["Age"].notnull()) & (df["Salary"].notnull()) & (df["Department"].notnull())].dropna()

   Employee_ID  Name   Age Department   Salary  Experience   City
0          101  Amit  25.0         IT  35000.0         2.0  Delhi