# fillna()

In [ ]:
# ==========================================
# fillna()
# ==========================================

# fillna() is used to replace missing values.

# Basic syntax:
# df["Column"].fillna(value)

# Text column:
# df["City"] = df["City"].fillna("Unknown")

# Numerical column:
# df["Quantity"] = df["Quantity"].fillna(0)

# Multiple columns:
# df = df.fillna({
#     "City": "Unknown",
#     "Department": "Unknown",
#     "Quantity": 0
# })

# fillna() normally returns a new result.
# To save the changes, assign the result back to df.

# Example:
# df["City"] = df["City"].fillna("Unknown")

In [17]:
import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    
    "Name": ["Amit", "Rahul", "Neha", "Pooja", "Rohit",
             "Sneha", "Vikas", "Kiran", "Ankit", "Priya"],
    
    "Department": ["IT", None, "HR", "Finance", None,
                   "Sales", "IT", None, "HR", "Finance"],
    
    "City": ["Delhi", "Jaipur", None, "Mumbai", "Pune",
             None, "Delhi", "Jaipur", None, "Pune"],
    
    "Age": [25, None, 29, 32, None, 27, 30, None, 26, 31],
    
    "Salary": [35000, 42000, None, 55000, 48000,
               None, 60000, 39000, None, 52000],
    
    "Experience": [2, 4, None, 8, 6, None, 10, 5, 2, None],
    
    "Bonus": [5000, None, 7000, 10000, None,
              6000, 12000, None, 5000, 8000]
}

df = pd.DataFrame(data)
df
# Fill all missing values in the DataFrame with 0
df.fillna(0)

# Fill all missing values in the DataFrame with "anand"
df.fillna("anand")

# Fill all missing values in the DataFrame with 10
df.fillna(10)

   Employee_ID   Name Department    City   Age   Salary  Experience    Bonus
0          101   Amit         IT   Delhi  25.0  35000.0         2.0   5000.0
1          102  Rahul         10  Jaipur  10.0  42000.0         4.0     10.0
2          103   Neha         HR      10  29.0     10.0        10.0   7000.0
3          104  Pooja    Finance  Mumbai  32.0  55000.0         8.0  10000.0
4          105  Rohit         10    Pune  10.0  48000.0         6.0     10.0
5          106  Sneha      Sales      10  27.0     10.0        10.0   6000.0
6          107  Vikas         IT   Delhi  30.0  60000.0        10.0  12000.0
7          108  Kiran         10  Jaipur  10.0  39000.0         5.0     10.0
8          109  Ankit         HR      10  26.0     10.0         2.0   5000.0
9          110  Priya    Finance    Pune  31.0  52000.0        10.0   8000.0

In [27]:
# Fill missing values in Age with 10
df["Age"].fillna(10)

# Fill missing values in Age with 20 and save the changes
df["Age"] = df["Age"].fillna(20)

# Check the DataFrame
df


# Fill missing values in Experience with 2 and save the changes
df["Experience"] = df["Experience"].fillna(2)

# Check the DataFrame
df


# Fill missing values in Salary with 30000 and save the changes
df["Salary"] = df["Salary"].fillna(30000)
df

   Employee_ID   Name Department    City   Age   Salary  Experience    Bonus
0          101   Amit         IT   Delhi  25.0  35000.0         2.0   5000.0
1          102  Rahul       None  Jaipur  20.0  42000.0         4.0      NaN
2          103   Neha         HR    None  29.0  30000.0         2.0   7000.0
3          104  Pooja    Finance  Mumbai  32.0  55000.0         8.0  10000.0
4          105  Rohit       None    Pune  20.0  48000.0         6.0      NaN
5          106  Sneha      Sales    None  27.0  30000.0         2.0   6000.0
6          107  Vikas         IT   Delhi  30.0  60000.0        10.0  12000.0
7          108  Kiran       None  Jaipur  20.0  39000.0         5.0      NaN
8          109  Ankit         HR    None  26.0  30000.0         2.0   5000.0
9          110  Priya    Finance    Pune  31.0  52000.0         2.0   8000.0

In [30]:
df["Age"].fillna(10) #Missing values 10 se fill karega, but change save nahi hoga.
df["Age"] = df["Age"].fillna(20)
df

   Employee_ID   Name Department    City   Age   Salary  Experience    Bonus
0          101   Amit         IT   Delhi  25.0  35000.0         2.0   5000.0
1          102  Rahul       None  Jaipur  20.0  42000.0         4.0      NaN
2          103   Neha         HR    None  29.0  30000.0         2.0   7000.0
3          104  Pooja    Finance  Mumbai  32.0  55000.0         8.0  10000.0
4          105  Rohit       None    Pune  20.0  48000.0         6.0      NaN
5          106  Sneha      Sales    None  27.0  30000.0         2.0   6000.0
6          107  Vikas         IT   Delhi  30.0  60000.0        10.0  12000.0
7          108  Kiran       None  Jaipur  20.0  39000.0         5.0      NaN
8          109  Ankit         HR    None  26.0  30000.0         2.0   5000.0
9          110  Priya    Finance    Pune  31.0  52000.0         2.0   8000.0

df["Column"].fillna(value)

        ↓
Fill karta hai, but change save nahi karta


df["Column"] = df["Column"].fillna(value)

        ↓
Fill karta hai + change save karta hai

In [37]:
# Fill missing values in multiple columns
# with different values.

df = df.fillna({
    "Age": 20,
    "Salary": 30000,
    "City": "Jaipur"
})
df

df=df.fillna({
    "Bonus":30000,
    "Daprtment":"it"
})
df

   Employee_ID   Name Department    City   Age   Salary  Experience    Bonus
0          101   Amit         IT   Delhi  25.0  35000.0         2.0   5000.0
1          102  Rahul       None  Jaipur  20.0  42000.0         4.0  30000.0
2          103   Neha         HR  jaipur  29.0  30000.0         2.0   7000.0
3          104  Pooja    Finance  Mumbai  32.0  55000.0         8.0  10000.0
4          105  Rohit       None    Pune  20.0  48000.0         6.0  30000.0
5          106  Sneha      Sales  jaipur  27.0  30000.0         2.0   6000.0
6          107  Vikas         IT   Delhi  30.0  60000.0        10.0  12000.0
7          108  Kiran       None  Jaipur  20.0  39000.0         5.0  30000.0
8          109  Ankit         HR  jaipur  26.0  30000.0         2.0   5000.0
9          110  Priya    Finance    Pune  31.0  52000.0         2.0   8000.0

In [46]:
# Q1 — Employee Data
# Department ki saari missing values ko "Unknown" se fill karo.

df["Department"]=df["Department"].fillna("unknown")
df

# Q2 — Employee Data
# Age ki missing values ko 25 se fill karo aur change original df mein save karo.

df["Age"]=df["Age"].fillna(25)
df

# Q3 — Salary Data
# Salary ki missing values ko 30000 se fill karo.

df["Salary"]=df["Salary"].fillna(30000)
df

# Q4 — Multiple Columns ⭐
# Ek hi fillna() command se: - Age → 25 ,- Salary → 35000 ,- Experience → 0 fill karo aur changes save karo.

df=df.fillna({
    "Age":25,
    "Salary":35000,
    "Experience":0
})
df

# Q5 — Real-Life Data Analyst Task 🔥
# Employee dataset ko clean karo: - Department → "Unknown" ,  - City → "Unknown" ,- Age → 25
# - Experience → 0 ,- Bonus → 0

df=df.fillna({
    "Department":"unknown",
    "City":"unknown",
    "Age":25,
    "Experience":0,
    "Bonus": 0
})
df

   Employee_ID   Name Department    City   Age   Salary  Experience    Bonus
0          101   Amit         IT   Delhi  25.0  35000.0         2.0   5000.0
1          102  Rahul    unknown  Jaipur  20.0  42000.0         4.0  30000.0
2          103   Neha         HR  jaipur  29.0  30000.0         2.0   7000.0
3          104  Pooja    Finance  Mumbai  32.0  55000.0         8.0  10000.0
4          105  Rohit    unknown    Pune  20.0  48000.0         6.0  30000.0
5          106  Sneha      Sales  jaipur  27.0  30000.0         2.0   6000.0
6          107  Vikas         IT   Delhi  30.0  60000.0        10.0  12000.0
7          108  Kiran    unknown  Jaipur  20.0  39000.0         5.0  30000.0
8          109  Ankit         HR  jaipur  26.0  30000.0         2.0   5000.0
9          110  Priya    Finance    Pune  31.0  52000.0         2.0   8000.0

# Fill Missing Values with Mean

In [47]:
# ==========================================
# Fill Missing Values with Mean
# ==========================================

# Mean = Average

# Syntax:
# df["Column"].mean()

# Fill missing values with mean:
# df["Column"] = df["Column"].fillna(
#     df["Column"].mean()
# )

# Example:
# df["Salary"] = df["Salary"].fillna(
#     df["Salary"].mean()
# )

# Mean is generally used for numerical columns.

# Mean Formula:
# Mean = Sum of values / Number of values

In [56]:
# Check the DataFrame
df

# Calculate mean of Salary
df["Salary"].mean()

# Fill missing Salary values with Salary mean
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

# Check the DataFrame
df


# Calculate mean of Age
df["Age"].mean()

# Fill missing Age values with Age mean
df["Age"] = df["Age"].fillna(df["Age"].mean())

# Check the DataFrame
df

   Employee_ID   Name Department    City   Age   Salary  Experience    Bonus
0          101   Amit         IT   Delhi  25.0  35000.0         2.0   5000.0
1          102  Rahul    unknown  Jaipur  20.0  42000.0         4.0  30000.0
2          103   Neha         HR  jaipur  29.0  30000.0         2.0   7000.0
3          104  Pooja    Finance  Mumbai  32.0  55000.0         8.0  10000.0
4          105  Rohit    unknown    Pune  20.0  48000.0         6.0  30000.0
5          106  Sneha      Sales  jaipur  27.0  30000.0         2.0   6000.0
6          107  Vikas         IT   Delhi  30.0  60000.0        10.0  12000.0
7          108  Kiran    unknown  Jaipur  20.0  39000.0         5.0  30000.0
8          109  Ankit         HR  jaipur  26.0  30000.0         2.0   5000.0
9          110  Priya    Finance    Pune  31.0  52000.0         2.0   8000.0

In [69]:
import pandas as pd

data = {
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
    
    "Product": ["Laptop", "Mobile", "Tablet", "Laptop", "Mobile",
                "Headphone", "Tablet", "Laptop", "Mobile", "Tablet"],
    
    "Quantity": [2, 3, None, 1, 4, None, 2, 3, None, 5],
    
    "Price": [55000, 25000, 30000, None, 22000,
              5000, 28000, None, 24000, 32000],
    
    "Customer_Age": [25, 30, None, 28, 35,
                     None, 27, 32, None, 29],
    
    "Sales": [110000, 75000, 60000, None, 88000,
              10000, 56000, 165000, None, 160000]
}

df_sales = pd.DataFrame(data)
df_sales
# Q1   Quantity column ka mean calculate karo.
df_sales["Quantity"].mean()


#Q2  Price column ka mean calculate karo.
df_sales["Price"].mean()

# Q3 Customer_Age mein jo missing values hain, unko Customer_Age ke mean se fill karo.
df_sales["Customer_Age"].mean()
df_sales["Customer_Age"]=df_sales["Customer_Age"].fillna(df_sales["Customer_Age"].mean())
df

# Q4  Quantity ki missing values ko Quantity ke mean se fill karo aur changes df_sales mein save karo
df_sales["Quantity"]=df_sales["Quantity"].fillna(df_sales["Quantity"].mean())
df_sales

# Q5 🔥 Real-Life Data Analyst Question
# Sales analysis ke liye:
# - Price ki missing values → Price ke mean se fill karo.
# - Sales ki missing values → Sales ke mean se fill karo.
# - Changes original df_sales mein save karo.
df_sales["Price"] = df_sales["Price"].fillna(df_sales["Price"].mean())

df_sales["Sales"] = df_sales["Sales"].fillna(df_sales["Sales"].mean())

# Fill Missing Values with Median

In [71]:
# ==========================================
# Fill Missing Values with Median
# ==========================================

# Median is the middle value after sorting the data.

# Calculate median:
# df["Column"].median()

# Fill missing values with median:
# df["Column"] = df["Column"].fillna(
#     df["Column"].median()
# )

# Example:
# df["Salary"] = df["Salary"].fillna(
#     df["Salary"].median()
# )

# Median is useful when data contains outliers.

In [82]:
import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    
    "Name": ["Amit", "Rahul", "Neha", "Pooja", "Rohit",
             "Sneha", "Vikas", "Kiran", "Ankit", "Priya"],
    
    "Age": [25, 28, None, 32, 27, None, 30, 26, None, 29],
    
    "Salary": [35000, 42000, None, 55000, 48000,
               None, 150000, 39000, None, 52000],
    
    "Experience": [2, 4, 3, None, 6, 5, None, 2, 4, None],
    
    "Performance_Score": [80, 85, None, 90, 88,
                          None, 95, 82, None, 91]
}

# Create DataFrame
df_median = pd.DataFrame(data)

# View DataFrame
df_median


# Calculate median of Salary
df_median["Salary"].median()

# Fill missing Salary values with Salary median
df_median["Salary"] = df_median["Salary"].fillna(
    df_median["Salary"].median()
)

# View DataFrame
df_median


# Calculate median of Age
df_median["Age"].median()

# Fill missing Age values with Age median
df_median["Age"] = df_median["Age"].fillna(
    df_median["Age"].median()
)

# View DataFrame
df_median

   Employee_ID   Name   Age    Salary  Experience  Performance_Score
0          101   Amit  25.0   35000.0         2.0               80.0
1          102  Rahul  28.0   42000.0         4.0               85.0
2          103   Neha  28.0   48000.0         3.0                NaN
3          104  Pooja  32.0   55000.0         NaN               90.0
4          105  Rohit  27.0   48000.0         6.0               88.0
5          106  Sneha  28.0   48000.0         5.0                NaN
6          107  Vikas  30.0  150000.0         NaN               95.0
7          108  Kiran  26.0   39000.0         2.0               82.0
8          109  Ankit  28.0   48000.0         4.0                NaN
9          110  Priya  29.0   52000.0         NaN               91.0

In [91]:
#Q1 Experience column ka median calculate karo.
df["Experience"].median()
df_median["Experience"]=df_median["Experience"].fillna(df_median["Experience"].median())
df_median

# Q2 Performance_Score column ka median calculate karo.

df_median["Performance_Score"].median()

#Q3 Experience ki missing values ko Experience ke median se fill karo aur changes save karo.
df_median["Experience"]=df["Experience"].fillna(df_median["Experience"].median())
df_median

# Q4 ⭐ Performance_Score ki missing values ko Performance_Score ke median se fill karo aur changes save karo.

df_median["Performance_Score"]=df_median["Performance_Score"].fillna(df_median["Performance_Score"].median())
df_median

   Employee_ID   Name   Age    Salary  Experience  Performance_Score
0          101   Amit  25.0   35000.0         2.0               80.0
1          102  Rahul  28.0   42000.0         4.0               85.0
2          103   Neha  28.0   48000.0         2.0               88.0
3          104  Pooja  32.0   55000.0         8.0               90.0
4          105  Rohit  27.0   48000.0         6.0               88.0
5          106  Sneha  28.0   48000.0         2.0               88.0
6          107  Vikas  30.0  150000.0        10.0               95.0
7          108  Kiran  26.0   39000.0         5.0               82.0
8          109  Ankit  28.0   48000.0         2.0               88.0
9          110  Priya  29.0   52000.0         2.0               91.0

In [99]:
  import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    
    "Name": [
        "Amit", "Rahul", "Neha", "Pooja", "Rohit",
        "Sneha", "Vikas", "Kiran", "Ankit", "Priya"
    ],
    
    "Department": [
        "IT", "HR", None, "IT", "Finance",
        "IT", None, "HR", "IT", None
    ],
    
    "City": [
        "Delhi", "Jaipur", "Delhi", None, "Mumbai",
        "Delhi", "Jaipur", None, "Delhi", "Mumbai"
    ],
    
    "Gender": [
        "Male", "Male", "Female", "Female", None,
        "Female", "Male", None, "Male", "Female"
    ],
    
    "Job_Role": [
        "Developer", "HR Executive", "Developer", None, "Accountant",
        "Developer", "Manager", "HR Executive", None, "Developer"
    ],
    
    "Age": [
        25, 28, 29, 32, 27,
        30, None, 26, 29, None
    ]
}

df_mode = pd.DataFrame(data)
# Mode find karna
df_mode["Department"].mode()

# First mode value lena
df_mode["Department"].mode()[0]

# Mode se missing values fill karna
df_mode["Department"] = df_mode["Department"].fillna(
    df_mode["Department"].mode()[0]
)
df_mode

   Employee_ID   Name Department    City  Gender      Job_Role   Age
0          101   Amit         IT   Delhi    Male     Developer  25.0
1          102  Rahul         HR  Jaipur    Male  HR Executive  28.0
2          103   Neha         IT   Delhi  Female     Developer  29.0
3          104  Pooja         IT    None  Female          None  32.0
4          105  Rohit    Finance  Mumbai    None    Accountant  27.0
5          106  Sneha         IT   Delhi  Female     Developer  30.0
6          107  Vikas         IT  Jaipur    Male       Manager   NaN
7          108  Kiran         HR    None    None  HR Executive  26.0
8          109  Ankit         IT   Delhi    Male          None  29.0
9          110  Priya         IT  Mumbai  Female     Developer   NaN

In [112]:
# Q1. Department column ka mode find karo.
df_mode["Department"].mode()

# Q2. Department ke missing values ko mode se fill karo.
df_mode["Department"]=df_mode["Department"].fillna(df_mode["Department"].mode()[0])
df_mode

# Q3. Gender column ka mode find karke missing values ko mode se fill karo.
df_mode["Gender"].mode()
df_mode["Gender"]=df_mode["Gender"].fillna(df_mode["Gender"].mode()[0])
df_mode

# Q4. Job_Role ke missing values ko mode se fill karo.
df_mode["Job_Role"].mode()
df_mode["Job_Role"]=df_mode["Job_Role"].fillna(df_mode["Job_Role"].mode()[0])
df_mode

# Q5. City ke missing values ko mode se fill karo.
df_mode["City"].mode()
df_mode["City"]=df_mode["City"].fillna(df_mode["City"].mode()[0])
df_mode

   Employee_ID   Name Department    City  Gender      Job_Role   Age
0          101   Amit         IT   Delhi    Male     Developer  25.0
1          102  Rahul         HR  Jaipur    Male  HR Executive  28.0
2          103   Neha         IT   Delhi  Female     Developer  29.0
3          104  Pooja         IT   Delhi  Female     Developer  32.0
4          105  Rohit    Finance  Mumbai  Female    Accountant  27.0
5          106  Sneha         IT   Delhi  Female     Developer  30.0
6          107  Vikas         IT  Jaipur    Male       Manager   NaN
7          108  Kiran         HR   Delhi  Female  HR Executive  26.0
8          109  Ankit         IT   Delhi    Male     Developer  29.0
9          110  Priya         IT  Mumbai  Female     Developer   NaN

# Forward Fill (ffill())

In [114]:
# Forward Fill (ffill) is used to fill missing values
# using the previous available value.

# Syntax:
# df["Column"] = df["Column"].ffill()

# Example:
# If values are:
# Delhi
# NaN
# NaN
# Jaipur

# After ffill:
# Delhi
# Delhi
# Delhi
# Jaipur

In [116]:
import pandas as pd

data = {
    "Employee": ["Amit", "Rahul", "Neha", "Pooja", "Rohit"],
    "City": ["Delhi", None, None, "Jaipur", None]
}

df = pd.DataFrame(data)

# Fill missing City values with the previous available value
df["City"] = df["City"].ffill()
df

  Employee    City
0     Amit   Delhi
1    Rahul   Delhi
2     Neha   Delhi
3    Pooja  Jaipur
4    Rohit  Jaipur

In [117]:
# ffill() = Forward Fill
# It uses the previous value to fill NaN.
# It works from TOP → BOTTOM.
# It is useful for sequential/time-series data.
# The first missing value remains missing if there is no previous value.

# Backward Fill (bfill())

In [118]:
# Backward Fill (bfill) is used to fill missing values
# using the next available value.

# Syntax:
# df["Column"] = df["Column"].bfill()

# Example:
# Before:
# Delhi
# NaN
# NaN
# Jaipur

# After bfill:
# Delhi
# Jaipur
# Jaipur
# Jaipur

In [121]:
import pandas as pd

data = {
    "Employee": ["Amit", "Rahul", "Neha", "Pooja", "Rohit"],
    "City": [None, None, "Delhi", "Jaipur", None]
}

df = pd.DataFrame(data)

# Fill missing City values using the next available value
df["City"] = df["City"].bfill()
df

  Employee    City
0     Amit   Delhi
1    Rahul   Delhi
2     Neha   Delhi
3    Pooja  Jaipur
4    Rohit    None

In [122]:
# bfill() = Backward Fill
# It uses the next available value to fill NaN.
# It works from BOTTOM → UP.
# It is useful for sequential/time-series data.
# If there is no value after a missing value, it remains missing.

In [134]:
import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Employee_Name": [
        "Amit", "Rahul", "Neha", "Pooja", "Rohit",
        "Sneha", "Vikas", "Kiran", "Ankit", "Priya"
    ],
    "Department": [
        "IT", None, None, "HR", None,
        "Finance", None, "IT", None, None
    ],
    "Shift": [
        "Morning", None, None, "Evening", None,
        "Night", None, "Morning", None, "Evening"
    ],
    "Manager": [
        None, None, "Raj", None, None,
        "Simran", None, None, "Aman", None
    ]
}

df = pd.DataFrame(data)
df

#Q1. Department column ke missing values ko previous available value se fill karo using ffill().

df["Department"].ffill()
df["Department"]=df["Department"].ffill()
df

# Q2. Shift column ke missing values ko next available value se fill karo using bfill().

df["Shift"]=df["Shift"].bfill()
df

# Q3. Manager column mein missing values ko ffill() se fill karo.
df["Manager"]=df["Manager"].ffill()
df

# Q4. Department column mein pehle ffill() aur phir bfill() apply karo, taaki maximum missing values fill ho saken.

df["Department"]=df["Department"].ffill()
df

df["Department"]=df["Department"].bfill()
df

   Employee_ID Employee_Name Department    Shift Manager
0          101          Amit         IT  Morning    None
1          102         Rahul         IT  Evening    None
2          103          Neha         IT  Evening     Raj
3          104         Pooja         HR  Evening     Raj
4          105         Rohit         HR    Night     Raj
5          106         Sneha    Finance    Night  Simran
6          107         Vikas    Finance  Morning  Simran
7          108         Kiran         IT  Morning  Simran
8          109         Ankit         IT  Evening    Aman
9          110         Priya         IT  Evening    Aman