 # duplicated()

In [1]:
# duplicated() → duplicate rows identify karta hai.

# True → Duplicate
# False → Not duplicate / first occurrence

# Count duplicates:
# df.duplicated().sum()

# Duplicate rows:
# df[df.duplicated()]

# Specific column:
# df.duplicated("Name")

# Multiple columns:
# df.duplicated(["Name", "City"])

# All duplicate occurrences:
# df.duplicated(keep=False)

In [3]:
import pandas as pd

data = {
    "Employee_ID": [
        101, 102, 103, 104, 105,
        106, 107, 108, 109, 110,
        102, 104, 107, 110, 111
    ],

    "Name": [
        "Amit", "Rahul", "Neha", "Pooja", "Rohit",
        "Sneha", "Vikas", "Kiran", "Ankit", "Priya",
        "Rahul", "Pooja", "Vikas", "Priya", "Mohit"
    ],

    "Department": [
        "IT", "HR", "Finance", "Sales", "IT",
        "HR", "IT", "Finance", "Sales", "IT",
        "HR", "Sales", "IT", "IT", "Marketing"
    ],

    "City": [
        "Delhi", "Jaipur", "Mumbai", "Pune", "Delhi",
        "Jaipur", "Delhi", "Mumbai", "Pune", "Delhi",
        "Jaipur", "Pune", "Delhi", "Delhi", "Ajmer"
    ],

    "Salary": [
        35000, 42000, 48000, 50000, 45000,
        39000, 55000, 46000, 41000, 52000,
        42000, 50000, 55000, 52000, 36000
    ]
}

df = pd.DataFrame(data)
df

    Employee_ID   Name Department    City  Salary
0           101   Amit         IT   Delhi   35000
1           102  Rahul         HR  Jaipur   42000
2           103   Neha    Finance  Mumbai   48000
3           104  Pooja      Sales    Pune   50000
4           105  Rohit         IT   Delhi   45000
5           106  Sneha         HR  Jaipur   39000
6           107  Vikas         IT   Delhi   55000
7           108  Kiran    Finance  Mumbai   46000
8           109  Ankit      Sales    Pune   41000
9           110  Priya         IT   Delhi   52000
10          102  Rahul         HR  Jaipur   42000
11          104  Pooja      Sales    Pune   50000
12          107  Vikas         IT   Delhi   55000
13          110  Priya         IT   Delhi   52000
14          111  Mohit  Marketing   Ajmer   36000

In [26]:
# Q1. Complete DataFrame mein duplicate rows identify karo.
df.duplicated()


# Q2. Complete DataFrame mein total duplicate rows count karo.
df.duplicated().sum()


# Q3. Sirf duplicate rows select karo.
df[df.duplicated()]


# Q4. Name column ke basis par duplicate records identify karo.
df.duplicated("Name")


# Q5. Name aur Salary dono columns ke basis par duplicate records identify karo.
df.duplicated(["Name", "Salary"])


# Q6. Employee_ID ke basis par duplicate records identify karo.
df.duplicated("Employee_ID")


# Q7. Employee_ID ke basis par total duplicate records count karo.
df.duplicated("Employee_ID").sum()


# Q8. Name column ke duplicate records ko select karo.
df[df.duplicated("Name")]


# Q9. Name aur City ke basis par duplicate records select karo.
df[df.duplicated(["Name", "City"])]


# Q10. Employee_ID ke basis par saare duplicate occurrences identify karo.
# keep=False ka use karo.
df.duplicated("Employee_ID", keep=False)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
14    False
dtype: bool

# drop_duplicates()

In [29]:
# drop_duplicates() is used to remove duplicate rows
# from a Pandas DataFrame.

# duplicated() → identifies duplicate rows
# drop_duplicates() → removes duplicate rows

# Syntax:
# df.drop_duplicates()

In [30]:
# Complete duplicate rows
df.drop_duplicates()

# Specific column
df.drop_duplicates("Name")

# Multiple columns
df.drop_duplicates(["Name", "Salary"])

# Keep first
df.drop_duplicates(keep="first")

# Keep last
df.drop_duplicates(keep="last")

# Remove all duplicate occurrences
df.drop_duplicates(keep=False)

# Permanently update DataFrame
df.drop_duplicates(inplace=True)

In [31]:
# duplicated()        → Duplicate identify
# duplicated().sum()  → Duplicate count
# df[df.duplicated()] → Duplicate rows show
# drop_duplicates()   → Duplicate remove

In [32]:
import pandas as pd

data = {
    "Order_ID": [
        1001, 1002, 1003, 1004, 1005,
        1006, 1007, 1008, 1009, 1010,
        1002, 1004, 1007, 1010, 1011
    ],

    "Customer": [
        "Amit", "Rahul", "Neha", "Pooja", "Rohit",
        "Sneha", "Vikas", "Kiran", "Ankit", "Priya",
        "Rahul", "Pooja", "Vikas", "Priya", "Mohit"
    ],

    "Product": [
        "Laptop", "Mobile", "Tablet", "Laptop", "Mobile",
        "Headphone", "Laptop", "Tablet", "Mobile", "Laptop",
        "Mobile", "Laptop", "Laptop", "Laptop", "Tablet"
    ],

    "City": [
        "Delhi", "Jaipur", "Mumbai", "Pune", "Delhi",
        "Jaipur", "Delhi", "Mumbai", "Pune", "Delhi",
        "Jaipur", "Pune", "Delhi", "Delhi", "Ajmer"
    ],

    "Amount": [
        55000, 25000, 30000, 60000, 22000,
        5000, 58000, 32000, 24000, 62000,
        25000, 60000, 58000, 62000, 35000
    ]
}

df = pd.DataFrame(data)

In [34]:
df

    Order_ID Customer    Product    City  Amount
0       1001     Amit     Laptop   Delhi   55000
1       1002    Rahul     Mobile  Jaipur   25000
2       1003     Neha     Tablet  Mumbai   30000
3       1004    Pooja     Laptop    Pune   60000
4       1005    Rohit     Mobile   Delhi   22000
5       1006    Sneha  Headphone  Jaipur    5000
6       1007    Vikas     Laptop   Delhi   58000
7       1008    Kiran     Tablet  Mumbai   32000
8       1009    Ankit     Mobile    Pune   24000
9       1010    Priya     Laptop   Delhi   62000
10      1002    Rahul     Mobile  Jaipur   25000
11      1004    Pooja     Laptop    Pune   60000
12      1007    Vikas     Laptop   Delhi   58000
13      1010    Priya     Laptop   Delhi   62000
14      1011    Mohit     Tablet   Ajmer   35000

In [46]:

# Q1. Complete DataFrame mein duplicate rows identify karo
# using duplicated().
df[df.duplicated()]

# Q2. Complete DataFrame mein total duplicate rows count karo.
df.duplicated().sum()

# Q3. Sirf duplicate rows ko select karo.
df[df.duplicated()]

# Q4. Order_ID ke basis par duplicate records identify karo.
df.duplicated("Order_ID")

# Q5. Customer aur City ke combination ke basis par
# duplicate records identify karo.
df.duplicated(["Customer","City"])

# Q6. Complete duplicate rows ko remove karo using
# drop_duplicates().
df.drop_duplicates()

# Q7. Order_ID ke basis par duplicate records remove karo.
df.drop_duplicates("Order_ID")

# Q8. Duplicate records remove karte time last occurrence
# ko keep karo.
df.drop_duplicates(keep="last")

# Q9. Duplicate records remove karo aur uske baad
# index ko 0 se reset karo.


# Q10. Order_ID ke basis par duplicate records ki
# saari occurrences identify karo using keep=False.

    Order_ID Customer    Product    City  Amount
0       1001     Amit     Laptop   Delhi   55000
2       1003     Neha     Tablet  Mumbai   30000
4       1005    Rohit     Mobile   Delhi   22000
5       1006    Sneha  Headphone  Jaipur    5000
7       1008    Kiran     Tablet  Mumbai   32000
8       1009    Ankit     Mobile    Pune   24000
10      1002    Rahul     Mobile  Jaipur   25000
11      1004    Pooja     Laptop    Pune   60000
12      1007    Vikas     Laptop   Delhi   58000
13      1010    Priya     Laptop   Delhi   62000
14      1011    Mohit     Tablet   Ajmer   35000