In [3]:
import pandas as pd
import pandas as pd

data = {
    "Name": ["Rahul", "Naveen", "Mohit", "Anand", "Neha"],
    "Age": [23, 28, 25, 32, 24],
    "City": ["Jaipur", "Delhi", "Ajmer", "Jaipur", "Mumbai"],
    "Department": ["IT", "HR", "Sales", "IT", "Finance"],
    "Salary": [35000, 42000, 30000, 55000, 38000]
}

df = pd.DataFrame(data)

df

     Name  Age    City Department  Salary
0   Rahul   23  Jaipur         IT   35000
1  Naveen   28   Delhi         HR   42000
2   Mohit   25   Ajmer      Sales   30000
3   Anand   32  Jaipur         IT   55000
4    Neha   24  Mumbai    Finance   38000

 1. Basic New Column   =  df["Gender"] = ["Male", "Male", "Female"] 

2. Same Value se New Column =  df["Country"] = "India"

3.  Existing Column se New Column =  df["Annual_Salary"] = df["Salary"] * 12

4.   Multiple Columns se New Column =  df["Total"] = df["Salary"] + df["Bonus"]

5.  Mathematical Operations ⭐
    Addition +  ,  Subtraction -  , Multiplication * , Division /  , Percentage %

6. Conditional New Column

7. Multiple Conditions 

8. String se New Column

9. Date/Time se New Column

10.

In [5]:
print(df)

     Name  Age    City Department  Salary
0   Rahul   23  Jaipur         IT   35000
1  Naveen   28   Delhi         HR   42000
2   Mohit   25   Ajmer      Sales   30000
3   Anand   32  Jaipur         IT   55000
4    Neha   24  Mumbai    Finance   38000

# 1. Basic New Column

In [12]:
df['gender']=['male','male','male', 'male' , 'female']
print(df)

df['experieces'] = [2,3,5,6,7]
print(df)

     Name  Age    City Department  Salary  gender  experieces
0   Rahul   23  Jaipur         IT   35000    male           2
1  Naveen   28   Delhi         HR   42000    male           3
2   Mohit   25   Ajmer      Sales   30000    male           5
3   Anand   32  Jaipur         IT   55000    male           6
4    Neha   24  Mumbai    Finance   38000  female           7
     Name  Age    City Department  Salary  gender  experieces
0   Rahul   23  Jaipur         IT   35000    male           2
1  Naveen   28   Delhi         HR   42000    male           3
2   Mohit   25   Ajmer      Sales   30000    male           5
3   Anand   32  Jaipur         IT   55000    male           6
4    Neha   24  Mumbai    Finance   38000  female           7

In [14]:
print(df)

     Name  Age    City Department  Salary  gender  experieces
0   Rahul   23  Jaipur         IT   35000    male           2
1  Naveen   28   Delhi         HR   42000    male           3
2   Mohit   25   Ajmer      Sales   30000    male           5
3   Anand   32  Jaipur         IT   55000    male           6
4    Neha   24  Mumbai    Finance   38000  female           7

# 2. Same Value se New Column

In [16]:
df['country']="india"
print(df)

     Name  Age    City Department  Salary  gender  experieces country
0   Rahul   23  Jaipur         IT   35000    male           2   india
1  Naveen   28   Delhi         HR   42000    male           3   india
2   Mohit   25   Ajmer      Sales   30000    male           5   india
3   Anand   32  Jaipur         IT   55000    male           6   india
4    Neha   24  Mumbai    Finance   38000  female           7   india

In [18]:
df["village"]="sultana"
print(df)

     Name  Age    City Department  Salary  gender  experieces country  village
0   Rahul   23  Jaipur         IT   35000    male           2   india  sultana
1  Naveen   28   Delhi         HR   42000    male           3   india  sultana
2   Mohit   25   Ajmer      Sales   30000    male           5   india  sultana
3   Anand   32  Jaipur         IT   55000    male           6   india  sultana
4    Neha   24  Mumbai    Finance   38000  female           7   india  sultana

In [21]:
df["status"]="active"
print(df)

     Name  Age    City Department  Salary  gender  experieces country  \
0   Rahul   23  Jaipur         IT   35000    male           2   india
1  Naveen   28   Delhi         HR   42000    male           3   india
2   Mohit   25   Ajmer      Sales   30000    male           5   india
3   Anand   32  Jaipur         IT   55000    male           6   india
4    Neha   24  Mumbai    Finance   38000  female           7   india

   village  status
0  sultana  active
1  sultana  active
2  sultana  active
3  sultana  active
4  sultana  active

# 3. Existing Column se New 

df["New_Column"] = df["Existing_Column"] + calculation

In [25]:
df["new_Salary"] =  df["Salary"] *12 
print(df)

     Name  Age    City Department  Salary  gender  experieces country  \
0   Rahul   23  Jaipur         IT  420000    male           2   india
1  Naveen   28   Delhi         HR  504000    male           3   india
2   Mohit   25   Ajmer      Sales  360000    male           5   india
3   Anand   32  Jaipur         IT  660000    male           6   india
4    Neha   24  Mumbai    Finance  456000  female           7   india

   village  status  new_Salary
0  sultana  active     5040000
1  sultana  active     6048000
2  sultana  active     4320000
3  sultana  active     7920000
4  sultana  active     5472000

In [28]:
df["new_city"] = df["City"] == "Jaipur" 
print(df)

     Name  Age    City Department  Salary  gender  experieces country  \
0   Rahul   23  Jaipur         IT  420000    male           2   india
1  Naveen   28   Delhi         HR  504000    male           3   india
2   Mohit   25   Ajmer      Sales  360000    male           5   india
3   Anand   32  Jaipur         IT  660000    male           6   india
4    Neha   24  Mumbai    Finance  456000  female           7   india

   village  status  new_Salary  new_city
0  sultana  active     5040000      True
1  sultana  active     6048000     False
2  sultana  active     4320000     False
3  sultana  active     7920000      True
4  sultana  active     5472000     False

In [32]:
# Annual salary
df["Annual_Salary"] = df["Salary"] * 12

# 10% bonus
df["Bonus"] = df["Salary"] * 0.10

# 5% salary increase
df["New_Salary"] = df["Salary"] * 1.05

# Salary after deduction
df["Net_Salary"] = df["Salary"] - 2000

In [33]:
print(df)

     Name  Age    City Department  Salary  gender  experieces country  \
0   Rahul   23  Jaipur         IT  420000    male           2   india
1  Naveen   28   Delhi         HR  504000    male           3   india
2   Mohit   25   Ajmer      Sales  360000    male           5   india
3   Anand   32  Jaipur         IT  660000    male           6   india
4    Neha   24  Mumbai    Finance  456000  female           7   india

   village  status  new_Salary  new_city  Annual_Salary    Bonus  New_Salary  \
0  sultana  active     5040000      True        5040000  42000.0    441000.0
1  sultana  active     6048000     False        6048000  50400.0    529200.0
2  sultana  active     4320000     False        4320000  36000.0    378000.0
3  sultana  active     7920000      True        7920000  66000.0    693000.0
4  sultana  active     5472000     False        5472000  45600.0    478800.0

   Net_Salary
0      418000
1      502000
2      358000
3      658000
4      454000

# 4. Multiple Columns se New Column
 Basic syntax:   df["New_Column"] = df["Column1"] + df["Column2"]

In [40]:
print(df)

df["salarys"] = df["new_Salary"]+ df["New_Salary"]
print(df)

df["location"] = df["City"] + "  " + df["village"]
print(df)

df["total_salary"] = df["Salary"] + df["new_Salary"] + df["Annual_Salary"] + df["New_Salary"]
print(df)

     Name  Age    City Department  Salary  gender  experieces country  \
0   Rahul   23  Jaipur         IT  420000    male           2   india
1  Naveen   28   Delhi         HR  504000    male           3   india
2   Mohit   25   Ajmer      Sales  360000    male           5   india
3   Anand   32  Jaipur         IT  660000    male           6   india
4    Neha   24  Mumbai    Finance  456000  female           7   india

   village  status  new_Salary  new_city  Annual_Salary    Bonus  New_Salary  \
0  sultana  active     5040000      True        5040000  42000.0    441000.0
1  sultana  active     6048000     False        6048000  50400.0    529200.0
2  sultana  active     4320000     False        4320000  36000.0    378000.0
3  sultana  active     7920000      True        7920000  66000.0    693000.0
4  sultana  active     5472000     False        5472000  45600.0    478800.0

   Net_Salary    salarys         location
0      418000  5481000.0  Jaipur  sultana
1      502000  6577200.0   Delhi  sultana
2      358000  4698000.0   Ajmer  sultana
3      658000  8613000.0  Jaipur  sultana
4      454000  5950800.0  Mumbai  sultana
     Name  Age    City Department  Salary  gender  experieces country  \
0   Rahul   23  Jaipur         IT  420000    male           2   india
1  Naveen   28   Delhi         HR  504000    male           3   india
2   Mohit   25   Ajmer      Sales  360000    male           5   india
3   Anand   32  Jaipur         IT  660000    male           6   india
4    Neha   24  Mumbai    Finance  456000  female           7   india

   village  status  new_Salary  new_city  Annual_Salary    Bonus  New_Salary  \
0  sultana  active     5040000      True        5040000  42000.0    441000.0
1  sultana  active     6048000     False        6048000  50400.0    529200.0
2  sultana  active     4320000     False        4320000  36000.0    378000.0
3  sultana  active     7920000      True        7920000  66000.0    693000.0
4  sultana  active     5472000     False        5472000  45600.0    478800.0

   Net_Salary    salarys         location
0      418000  5481000.0  Jaipur  sultana
1      502000  6577200.0   Delhi  sultana
2      358000  4698000.0   Ajmer  sultana
3      658000  8613000.0  Jaipur  sultana
4      454000  5950800.0  Mumbai  sultana
     Name  Age    City Department  Salary  gender  experieces country  \
0   Rahul   23  Jaipur         IT  420000    male           2   india
1  Naveen   28   Delhi         HR  504000    male           3   india
2   Mohit   25   Ajmer      Sales  360000    male           5   india
3   Anand   32  Jaipur         IT  660000    male           6   india
4    Neha   24  Mumbai    Finance  456000  female           7   india

   village  status  new_Salary  new_city  Annual_Salary    Bonus  New_Salary  \
0  sultana  active     5040000      True        5040000  42000.0    441000.0
1  sultana  active     6048000     False        6048000  50400.0    529200.0
2  sultana  active     4320000     False        4320000  36000.0    378000.0
3  sultana  active     7920000      True        7920000  66000.0    693000.0
4  sultana  active     5472000     False        5472000  45600.0    478800.0

   Net_Salary    salarys         location
0      418000  5481000.0  Jaipur  sultana
1      502000  6577200.0   Delhi  sultana
2      358000  4698000.0   Ajmer  sultana
3      658000  8613000.0  Jaipur  sultana
4      454000  5950800.0  Mumbai  sultana
     Name  Age    City Department  Salary  gender  experieces country  \
0   Rahul   23  Jaipur         IT  420000    male           2   india
1  Naveen   28   Delhi         HR  504000    male           3   india
2   Mohit   25   Ajmer      Sales  360000    male           5   india
3   Anand   32  Jaipur         IT  660000    male           6   india
4    Neha   24  Mumbai    Finance  456000  female           7   india

   village  status  new_Salary  new_city  Annual_Salary    Bonus  New_Salary  \
0  sultana  active     5040000      True        5040000  42000.0    441000.0
1  sultana  active     6048000     False        6048000  50400.0    529200.0
2  sultana  active     4320000     False        4320000  36000.0    378000.0
3  sultana  active     7920000      True        7920000  66000.0    693000.0
4  sultana  active     5472000     False        5472000  45600.0    478800.0

   Net_Salary    salarys         location  total_salary
0      418000  5481000.0  Jaipur  sultana    10941000.0
1      502000  6577200.0   Delhi  sultana    13129200.0
2      358000  4698000.0   Ajmer  sultana     9378000.0
3      658000  8613000.0  Jaipur  sultana    17193000.0
4      454000  5950800.0  Mumbai  sultana    11878800.0

# 6. Conditional New Column
1. np.where() =  np.where(condition, value_if_true, value_if_false)

In [42]:
data = {
    "Name": ["Rahul", "Naveen", "Mohit", "Anand", "Neha"],
    "Age": [23, 28, 25, 32, 24],
    "Salary": [35000, 42000, 30000, 55000, 38000]
}

df = pd.DataFrame(data)

df

     Name  Age  Salary
0   Rahul   23   35000
1  Naveen   28   42000
2   Mohit   25   30000
3   Anand   32   55000
4    Neha   24   38000

In [54]:
import pandas as pd
import numpy as np
df["Age_Status"] = np.where(
    df["Age"] >= 25,
    "Adult",
    "Young"
)
print(df)

     Name  Age  Salary Age_Status
0   Rahul   23   35000      Young
1  Naveen   28   42000      Adult
2   Mohit   25   30000      Adult
3   Anand   32   55000      Adult
4    Neha   24   38000      Young

In [56]:
  df["salary_status"]= np.where(
      df["Salary"]>=35000,
      "high",
      "low"
  )
print(df)

     Name  Age  Salary Age_Status salary_status
0   Rahul   23   35000      Young          high
1  Naveen   28   42000      Adult          high
2   Mohit   25   30000      Adult           low
3   Anand   32   55000      Adult          high
4    Neha   24   38000      Young          high

 #  TOPIC 8: STRING SE NEW COLUMN
  Common operations:
   1 .str.upper()
   
2   .str.lower()

3 .str.title()

4 .str.strip()

5 .str.split()

6 .str.len()

In [58]:
import pandas as pd

data = {
    "Name": ["Rahul Verma", "Naveen Kumar", "Mohit Sharma", "Anand Singh"],
    "City": ["Jaipur", "Delhi", "Ajmer", "Mumbai"]
}

df = pd.DataFrame(data)

df

           Name    City
0   Rahul Verma  Jaipur
1  Naveen Kumar   Delhi
2  Mohit Sharma   Ajmer
3   Anand Singh  Mumbai

In [73]:
# 1. Original DataFrame ko print karna
print(df)

# 2. String ko UPPERCASE mein convert karke new column banana
# .str.upper()
df["new_name"] = df["Name"].str.upper()
print(df)

# 3. String ko lowercase mein convert karke new column banana
# .str.lower()
df["new_name2"] = df["Name"].str.lower()
print(df)

# 4. String ko Title Case mein convert karke new column banana
# .str.title()
df["df_name3"] = df["Name"].str.title()
print(df)

# 5. String ko words/list mein split karna
# .str.split()
df["new_name4"] = df["Name"].str.split()
print(df)

# 6. Split ke baad first word select karna
# .str.split().str[0]
# Example: "Rahul Verma" → "Rahul"
df["new_name5"] = df["Name"].str.split().str[0]
print(df)

# 7. String ki length nikalna
# .str.len()
df["length"] = df["Name"].str.len()
print(df)

           Name    City      new_name     new_name2      df_name3  \
0   Rahul Verma  Jaipur   RAHUL VERMA   rahul verma   Rahul Verma
1  Naveen Kumar   Delhi  NAVEEN KUMAR  naveen kumar  Naveen Kumar
2  Mohit Sharma   Ajmer  MOHIT SHARMA  mohit sharma  Mohit Sharma
3   Anand Singh  Mumbai   ANAND SINGH   anand singh   Anand Singh

         new_name4 new_name5  length
0   [Rahul, Verma]     Rahul      11
1  [Naveen, Kumar]    Naveen      12
2  [Mohit, Sharma]     Mohit      12
3   [Anand, Singh]     Anand      11
           Name    City      new_name     new_name2      df_name3  \
0   Rahul Verma  Jaipur   RAHUL VERMA   rahul verma   Rahul Verma
1  Naveen Kumar   Delhi  NAVEEN KUMAR  naveen kumar  Naveen Kumar
2  Mohit Sharma   Ajmer  MOHIT SHARMA  mohit sharma  Mohit Sharma
3   Anand Singh  Mumbai   ANAND SINGH   anand singh   Anand Singh

         new_name4 new_name5  length
0   [Rahul, Verma]     Rahul      11
1  [Naveen, Kumar]    Naveen      12
2  [Mohit, Sharma]     Mohit      12
3   [Anand, Singh]     Anand      11
           Name    City      new_name     new_name2      df_name3  \
0   Rahul Verma  Jaipur   RAHUL VERMA   rahul verma   Rahul Verma
1  Naveen Kumar   Delhi  NAVEEN KUMAR  naveen kumar  Naveen Kumar
2  Mohit Sharma   Ajmer  MOHIT SHARMA  mohit sharma  Mohit Sharma
3   Anand Singh  Mumbai   ANAND SINGH   anand singh   Anand Singh

         new_name4 new_name5  length
0   [Rahul, Verma]     Rahul      11
1  [Naveen, Kumar]    Naveen      12
2  [Mohit, Sharma]     Mohit      12
3   [Anand, Singh]     Anand      11
           Name    City      new_name     new_name2      df_name3  \
0   Rahul Verma  Jaipur   RAHUL VERMA   rahul verma   Rahul Verma
1  Naveen Kumar   Delhi  NAVEEN KUMAR  naveen kumar  Naveen Kumar
2  Mohit Sharma   Ajmer  MOHIT SHARMA  mohit sharma  Mohit Sharma
3   Anand Singh  Mumbai   ANAND SINGH   anand singh   Anand Singh

         new_name4 new_name5  length
0   [Rahul, Verma]     Rahul      11
1  [Naveen, Kumar]    Naveen      12
2  [Mohit, Sharma]     Mohit      12
3   [Anand, Singh]     Anand      11
           Name    City      new_name     new_name2      df_name3  \
0   Rahul Verma  Jaipur   RAHUL VERMA   rahul verma   Rahul Verma
1  Naveen Kumar   Delhi  NAVEEN KUMAR  naveen kumar  Naveen Kumar
2  Mohit Sharma   Ajmer  MOHIT SHARMA  mohit sharma  Mohit Sharma
3   Anand Singh  Mumbai   ANAND SINGH   anand singh   Anand Singh

         new_name4 new_name5  length
0   [Rahul, Verma]     Rahul      11
1  [Naveen, Kumar]    Naveen      12
2  [Mohit, Sharma]     Mohit      12
3   [Anand, Singh]     Anand      11
           Name    City      new_name     new_name2      df_name3  \
0   Rahul Verma  Jaipur   RAHUL VERMA   rahul verma   Rahul Verma
1  Naveen Kumar   Delhi  NAVEEN KUMAR  naveen kumar  Naveen Kumar
2  Mohit Sharma   Ajmer  MOHIT SHARMA  mohit sharma  Mohit Sharma
3   Anand Singh  Mumbai   ANAND SINGH   anand singh   Anand Singh

         new_name4 new_name5  length
0   [Rahul, Verma]     Rahul      11
1  [Naveen, Kumar]    Naveen      12
2  [Mohit, Sharma]     Mohit      12
3   [Anand, Singh]     Anand      11
           Name    City      new_name     new_name2      df_name3  \
0   Rahul Verma  Jaipur   RAHUL VERMA   rahul verma   Rahul Verma
1  Naveen Kumar   Delhi  NAVEEN KUMAR  naveen kumar  Naveen Kumar
2  Mohit Sharma   Ajmer  MOHIT SHARMA  mohit sharma  Mohit Sharma
3   Anand Singh  Mumbai   ANAND SINGH   anand singh   Anand Singh

         new_name4 new_name5  length
0   [Rahul, Verma]     Rahul      11
1  [Naveen, Kumar]    Naveen      12
2  [Mohit, Sharma]     Mohit      12
3   [Anand, Singh]     Anand      11

1. .str.upper()       → UPPERCASE
2. .str.lower()       → lowercase
3. .str.title()       → Title Case
4. .str.split()       → String ko split karna
5. .str.split().str[0] → First word select karna
6. .str.len()         → String length

# Date & Time

In [76]:
data = {
    "Name": ["Rahul", "Naveen", "Mohit"],
    "Joining_Date": ["2023-05-10", "2022-08-15", "2024-01-20"]
}

df = pd.DataFrame(data)

df

     Name Joining_Date
0   Rahul   2023-05-10
1  Naveen   2022-08-15
2   Mohit   2024-01-20

pd.to_datetime()

String ko proper datetime mein convert karne ke liye:

In [86]:
df["Joining_Date"]=pd.to_datetime(df["Joining_Date"])
print(df)

     Name Joining_Date joining_date
0   Rahul   2023-05-10   2023-05-10
1  Naveen   2022-08-15   2022-08-15
2   Mohit   2024-01-20   2024-01-20

String Date

    ↓
pd.to_datetime()

    ↓
Datetime

In [98]:
df["year"]=df["Joining_Date"].dt.year
print(df)

df["month"]=df["Joining_Date"].dt.month
print(df)

df["day"]=df["Joining_Date"].dt.day
print(df)

df["month_name"]=df["Joining_Date"].dt.month_name()
print(df)

df["day_name"]=df["Joining_Date"].dt.day_name()
print(df)

     Name Joining_Date joining_date  year  month  day month_name   day_name
0   Rahul   2023-05-10   2023-05-10  2023      5   10        May  Wednesday
1  Naveen   2022-08-15   2022-08-15  2022      8   15     August     Monday
2   Mohit   2024-01-20   2024-01-20  2024      1   20    January   Saturday
     Name Joining_Date joining_date  year  month  day month_name   day_name
0   Rahul   2023-05-10   2023-05-10  2023      5   10        May  Wednesday
1  Naveen   2022-08-15   2022-08-15  2022      8   15     August     Monday
2   Mohit   2024-01-20   2024-01-20  2024      1   20    January   Saturday
     Name Joining_Date joining_date  year  month  day month_name   day_name
0   Rahul   2023-05-10   2023-05-10  2023      5   10        May  Wednesday
1  Naveen   2022-08-15   2022-08-15  2022      8   15     August     Monday
2   Mohit   2024-01-20   2024-01-20  2024      1   20    January   Saturday
     Name Joining_Date joining_date  year  month  day month_name   day_name
0   Rahul   2023-05-10   2023-05-10  2023      5   10        May  Wednesday
1  Naveen   2022-08-15   2022-08-15  2022      8   15     August     Monday
2   Mohit   2024-01-20   2024-01-20  2024      1   20    January   Saturday
     Name Joining_Date joining_date  year  month  day month_name   day_name
0   Rahul   2023-05-10   2023-05-10  2023      5   10        May  Wednesday
1  Naveen   2022-08-15   2022-08-15  2022      8   15     August     Monday
2   Mohit   2024-01-20   2024-01-20  2024      1   20    January   Saturday

In [113]:
data = {
    "Name": ["Rahul", "Naveen", "Mohit", "Anand"],
    "Joining_Date": [
        "2023-05-10",
        "2022-08-15",
        "2024-01-20",
        "2021-12-25"
    ]
}

df = pd.DataFrame(data)
print(df)

df["joining_date"]=pd.to_datetime(df["Joining_Date"])# String ko datetime mein convert karta hai.
print(df)


df["year"]=df["joining_date"].dt.year  #➡️ Year
print(df)

df['month']=df["joining_date"].dt.month  #➡️ Month number
print(df)

df["day"]=df["joining_date"].dt.day  #➡️ Day
print(df)

df["month_name"]=df["joining_date"].dt.month_name()   # ➡️ Month name
print(df)

df["day_name"]=df["joining_date"].dt.day_name()   #➡️ Day name
print(df)

     Name Joining_Date
0   Rahul   2023-05-10
1  Naveen   2022-08-15
2   Mohit   2024-01-20
3   Anand   2021-12-25
     Name Joining_Date joining_date
0   Rahul   2023-05-10   2023-05-10
1  Naveen   2022-08-15   2022-08-15
2   Mohit   2024-01-20   2024-01-20
3   Anand   2021-12-25   2021-12-25
     Name Joining_Date joining_date  year
0   Rahul   2023-05-10   2023-05-10  2023
1  Naveen   2022-08-15   2022-08-15  2022
2   Mohit   2024-01-20   2024-01-20  2024
3   Anand   2021-12-25   2021-12-25  2021
     Name Joining_Date joining_date  year  month
0   Rahul   2023-05-10   2023-05-10  2023      5
1  Naveen   2022-08-15   2022-08-15  2022      8
2   Mohit   2024-01-20   2024-01-20  2024      1
3   Anand   2021-12-25   2021-12-25  2021     12
     Name Joining_Date joining_date  year  month  day
0   Rahul   2023-05-10   2023-05-10  2023      5   10
1  Naveen   2022-08-15   2022-08-15  2022      8   15
2   Mohit   2024-01-20   2024-01-20  2024      1   20
3   Anand   2021-12-25   2021-12-25  2021     12   25
     Name Joining_Date joining_date  year  month  day month_name
0   Rahul   2023-05-10   2023-05-10  2023      5   10        May
1  Naveen   2022-08-15   2022-08-15  2022      8   15     August
2   Mohit   2024-01-20   2024-01-20  2024      1   20    January
3   Anand   2021-12-25   2021-12-25  2021     12   25   December
     Name Joining_Date joining_date  year  month  day month_name   day_name
0   Rahul   2023-05-10   2023-05-10  2023      5   10        May  Wednesday
1  Naveen   2022-08-15   2022-08-15  2022      8   15     August     Monday
2   Mohit   2024-01-20   2024-01-20  2024      1   20    January   Saturday
3   Anand   2021-12-25   2021-12-25  2021     12   25   December   Saturday