In [7]:
import pandas as pd
data={
    'name':['anand','rahul','mohit','ram'],
    'age':[23,24,25,21],
    'deepartments':['it','hr','it','hr']
}
df=pd.DataFrame(data)
print(df)
print(df.size)
print(df.ndim)
print(df.shape)

    name  age deepartments
0  anand   23           it
1  rahul   24           hr
2  mohit   25           it
3    ram   21           hr
12
2
(4, 3)

In [11]:
data = [
    ['rahul', 23, 'jaipur'],
    ['naveen', 43, 'delhi'],
    ['mohit', 21, 'ajmer'],
    ['anand', 32, 'jaipur']
]

df = pd.DataFrame(
    data,
    columns=['name', 'age', 'city']
)

print(df)

     name  age    city
0   rahul   23  jaipur
1  naveen   43   delhi
2   mohit   21   ajmer
3   anand   32  jaipur

In [13]:
import pandas as pd

data = {
    "Name": ["Rahul", "Naveen", "Mohit", "Anand", "Neha",
             "Priya", "Rohit", "Pooja", "Amit", "Sneha"],

    "Age": [23, 28, 25, 32, 24, 27, 30, 26, 29, 31],

    "City": ["Jaipur", "Delhi", "Ajmer", "Jaipur", "Mumbai",
             "Delhi", "Pune", "Ajmer", "Mumbai", "Pune"],

    "Department": ["IT", "HR", "Sales", "IT", "Finance",
                   "Marketing", "IT", "HR", "Sales", "Finance"],

    "Salary": [35000, 42000, 30000, 55000, 38000,
               45000, 50000, 36000, 41000, 48000]
}

df = pd.DataFrame(data)

print(df)

     Name  Age    City Department  Salary
0   Rahul   23  Jaipur         IT   35000
1  Naveen   28   Delhi         HR   42000
2   Mohit   25   Ajmer      Sales   30000
3   Anand   32  Jaipur         IT   55000
4    Neha   24  Mumbai    Finance   38000
5   Priya   27   Delhi  Marketing   45000
6   Rohit   30    Pune         IT   50000
7   Pooja   26   Ajmer         HR   36000
8    Amit   29  Mumbai      Sales   41000
9   Sneha   31    Pune    Finance   48000

# Selection and Indexing of Columns
#Single column =  df["Name"]


 Multiple columns =  df[["Name", "City"]]


 Column by label  =   df.loc[:, "Name"]


 Column by position  = df.iloc[:, 0]


 Multiple columns by position ==  df.iloc[:, 0:3]

In [14]:
import pandas as pd

data = {
    "Name": ["Rahul", "Naveen", "Mohit", "Anand", "Neha"],
    "Age": [23, 28, 25, 32, 24],
    "City": ["Jaipur", "Delhi", "Ajmer", "Jaipur", "Mumbai"],
    "Department": ["IT", "HR", "Sales", "IT", "Finance"],
    "Salary": [35000, 42000, 30000, 55000, 38000]
}

df = pd.DataFrame(data)

df

     Name  Age    City Department  Salary
0   Rahul   23  Jaipur         IT   35000
1  Naveen   28   Delhi         HR   42000
2   Mohit   25   Ajmer      Sales   30000
3   Anand   32  Jaipur         IT   55000
4    Neha   24  Mumbai    Finance   38000

In [25]:
# 1. Single Column Select Karna
print(df['Name'])
print(df['Age'])
print(df['City'])
print(df['Department'])

0     Rahul
1    Naveen
2     Mohit
3     Anand
4      Neha
Name: Name, dtype: object
0    23
1    28
2    25
3    32
4    24
Name: Age, dtype: int64
0    Jaipur
1     Delhi
2     Ajmer
3    Jaipur
4    Mumbai
Name: City, dtype: object
0         IT
1         HR
2      Sales
3         IT
4    Finance
Name: Department, dtype: object

In [25]:
# 1. Single Column Select Karna
print(df['Name'])
print(df['Age'])
print(df['City'])
print(df['Department'])

0     Rahul
1    Naveen
2     Mohit
3     Anand
4      Neha
Name: Name, dtype: object
0    23
1    28
2    25
3    32
4    24
Name: Age, dtype: int64
0    Jaipur
1     Delhi
2     Ajmer
3    Jaipur
4    Mumbai
Name: City, dtype: object
0         IT
1         HR
2      Sales
3         IT
4    Finance
Name: Department, dtype: object

In [32]:
# 2. Multiple Columns Select Karna
df
print(df[['Name','Age']])
df[['Department','Age']]
df[['Name',"Age","Department"]]

     Name  Age
0   Rahul   23
1  Naveen   28
2   Mohit   25
3   Anand   32
4    Neha   24

     Name  Age Department
0   Rahul   23         IT
1  Naveen   28         HR
2   Mohit   25      Sales
3   Anand   32         IT
4    Neha   24    Finance

In [34]:
df["Name"]                 # Single column
df[["Name", "Salary"]]     # Multiple columns

     Name  Salary
0   Rahul   35000
1  Naveen   42000
2   Mohit   30000
3   Anand   55000
4    Neha   38000

In [44]:
# 3. Column ko Position se Select Karna
# .iloc[] se column ki position ke according select kar sakte hain.
# df.iloc[:, 0]
# :  → All rows
# 0  → First column
print(df)
print(df.iloc[: , 2])
print(df.iloc[: , 3])
print(df.iloc[: , 0])
print(df.iloc[: , 1])

     Name  Age    City Department  Salary
0   Rahul   23  Jaipur         IT   35000
1  Naveen   28   Delhi         HR   42000
2   Mohit   25   Ajmer      Sales   30000
3   Anand   32  Jaipur         IT   55000
4    Neha   24  Mumbai    Finance   38000
0    Jaipur
1     Delhi
2     Ajmer
3    Jaipur
4    Mumbai
Name: City, dtype: object
0         IT
1         HR
2      Sales
3         IT
4    Finance
Name: Department, dtype: object
0     Rahul
1    Naveen
2     Mohit
3     Anand
4      Neha
Name: Name, dtype: object
0    23
1    28
2    25
3    32
4    24
Name: Age, dtype: int64

In [49]:
#4. Multiple Columns Position se

print(df)
print(df.iloc[: , 0:2])
print(df.iloc[:, 1:3])
print(df.iloc[: , 0:3])

     Name  Age    City Department  Salary
0   Rahul   23  Jaipur         IT   35000
1  Naveen   28   Delhi         HR   42000
2   Mohit   25   Ajmer      Sales   30000
3   Anand   32  Jaipur         IT   55000
4    Neha   24  Mumbai    Finance   38000
     Name  Age
0   Rahul   23
1  Naveen   28
2   Mohit   25
3   Anand   32
4    Neha   24
   Age    City
0   23  Jaipur
1   28   Delhi
2   25   Ajmer
3   32  Jaipur
4   24  Mumbai
     Name  Age    City
0   Rahul   23  Jaipur
1  Naveen   28   Delhi
2   Mohit   25   Ajmer
3   Anand   32  Jaipur
4    Neha   24  Mumbai

In [55]:
# 5. .loc[] se Column Select
#  Column name ke according select karna:
# Label/name based selection.
print(df)
print(df.loc[: , 'Name'])
print(df.loc[: , ['Name','City']])

     Name  Age    City Department  Salary
0   Rahul   23  Jaipur         IT   35000
1  Naveen   28   Delhi         HR   42000
2   Mohit   25   Ajmer      Sales   30000
3   Anand   32  Jaipur         IT   55000
4    Neha   24  Mumbai    Finance   38000
0     Rahul
1    Naveen
2     Mohit
3     Anand
4      Neha
Name: Name, dtype: object
     Name    City
0   Rahul  Jaipur
1  Naveen   Delhi
2   Mohit   Ajmer
3   Anand  Jaipur
4    Neha  Mumbai

# Selecting Rows
1. First Row Select Karna :   df.iloc[0]
2. Second Row Select Karna :   df.iloc[1]
3. 0 → First row, 
   1 → Second row , 
   2 → Third row , 
   3 → Fourth row , 
   4 → Fifth row

4.  Multiple Rows Select Karna  : df.iloc[0:3]
5.  Last Row Select Karna
6.  .loc[] Se Row Select Karna

In [67]:
import pandas as pd

data = {
    "Name": ["Rahul", "Naveen", "Mohit", "Anand", "Neha"],
    "Age": [23, 28, 25, 32, 24],
    "City": ["Jaipur", "Delhi", "Ajmer", "Jaipur", "Mumbai"],
    "Department": ["IT", "HR", "Sales", "IT", "Finance"],
    "Salary": [35000, 42000, 30000, 55000, 38000]
}

df = pd.DataFrame(data)

print(df)
print(df.iloc[0])  #0 first row ka position hai.
print(df.iloc[2])  

print(df.iloc[0:2]) # Multiple Rows Select Karna
print(df.iloc[0:4]) # 0,1,2,3 rows 

print(df.loc[0]) 
print(df.loc[0:3]) # → 0, 1, 2 , 3 rows

     Name  Age    City Department  Salary
0   Rahul   23  Jaipur         IT   35000
1  Naveen   28   Delhi         HR   42000
2   Mohit   25   Ajmer      Sales   30000
3   Anand   32  Jaipur         IT   55000
4    Neha   24  Mumbai    Finance   38000
Name           Rahul
Age               23
City          Jaipur
Department        IT
Salary         35000
Name: 0, dtype: object
Name          Mohit
Age              25
City          Ajmer
Department    Sales
Salary        30000
Name: 2, dtype: object
     Name  Age    City Department  Salary
0   Rahul   23  Jaipur         IT   35000
1  Naveen   28   Delhi         HR   42000
     Name  Age    City Department  Salary
0   Rahul   23  Jaipur         IT   35000
1  Naveen   28   Delhi         HR   42000
2   Mohit   25   Ajmer      Sales   30000
3   Anand   32  Jaipur         IT   55000
Name           Rahul
Age               23
City          Jaipur
Department        IT
Salary         35000
Name: 0, dtype: object
     Name  Age    City Department  Salary
0   Rahul   23  Jaipur         IT   35000
1  Naveen   28   Delhi         HR   42000
2   Mohit   25   Ajmer      Sales   30000
3   Anand   32  Jaipur         IT   55000

In [82]:
 # Condition ke Basis Par Row Select Karna
print(df)
print(df[df["Age"]>30])

print(df[df["Salary"]> 35000])
print(df[df['City'] == 'Jaipur'])

     Name  Age    City Department  Salary
0   Rahul   23  Jaipur         IT   35000
1  Naveen   28   Delhi         HR   42000
2   Mohit   25   Ajmer      Sales   30000
3   Anand   32  Jaipur         IT   55000
4    Neha   24  Mumbai    Finance   38000
    Name  Age    City Department  Salary
3  Anand   32  Jaipur         IT   55000
     Name  Age    City Department  Salary
1  Naveen   28   Delhi         HR   42000
3   Anand   32  Jaipur         IT   55000
4    Neha   24  Mumbai    Finance   38000
    Name  Age    City Department  Salary
0  Rahul   23  Jaipur         IT   35000
3  Anand   32  Jaipur         IT   55000

In [83]:
# 1. Position se
df.iloc[0]

# 2. Label se
df.loc[0]

# 3. Condition se
df[df["Age"] > 25]

     Name  Age    City Department  Salary
1  Naveen   28   Delhi         HR   42000
3   Anand   32  Jaipur         IT   55000